### ISSUE TITLE
那些真的需要搜索引擎，而且只能用百度的怎么办？

### ISSUE THREAD

**Issue by joostshao** [xiaojiaqi/Freeeedoooom#1]
那些真的需要搜索引擎，而且只能用百度的怎么办？

**Comment by xiaojiaqi** [comment]
工具只是混淆你的搜索，并不是攻击搜索引擎。简单的说，工具只是伪装了很多次搜索，让推荐算法不了解你到底对什么感兴趣。让推荐算法失效
